# This is a basic workflow to help you get started with Actions

name: update

# Controls when the action will run. 
on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.52.0
        with:
          ruby-version: 2.7
      - name: install dependencies
        run: |
          npm install
          pip install mkdocs==0.17.5
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          bundle install
      - name: Unit tests
        run: npm run test
      - name: Crawl site
        run: |
          npm run serve & npm run crawl
          kill -9 $!
